package com.ipos.pu.ui.controller;

import com.ipos.pu.model.Campaign;
import com.ipos.pu.repository.CampaignRepository;
import com.ipos.pu.service.CartService;
import com.ipos.pu.service.ReportService;
import com.ipos.pu.ui.SceneManager;
import com.ipos.pu.ui.SessionManager;
import javafx.fxml.FXML;
import javafx.print.PrinterJob;
import javafx.scene.control.*;
import javafx.scene.text.Font;
import javafx.scene.text.Text;
import org.springframework.stereotype.Component;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

@Component
public class ReportsController {

    private final ReportService reportService;
    private final CartService cartService;
    private final CampaignRepository campaignRepository;

    @FXML private DatePicker startDatePicker;
    @FXML private DatePicker endDatePicker;
    @FXML private TextArea reportOutput;
    @FXML private Label welcomeLabel;
    @FXML private Button cartNavButton;
    @FXML private ComboBox<String> campaignCombo;

    private List<Campaign> loadedCampaigns;

    public ReportsController(ReportService reportService, CartService cartService,
                              CampaignRepository campaignRepository) {
        this.reportService = reportService;
        this.cartService = cartService;
        this.campaignRepository = campaignRepository;
    }

    @FXML
    public void initialize() {
        startDatePicker.setValue(LocalDate.now().minusMonths(1));
        endDatePicker.setValue(LocalDate.now());

        if (SessionManager.isLoggedIn()) {
            welcomeLabel.setText(SessionManager.getCurrentMember().getFirstName());
            Long memberId = SessionManager.getCurrentMember().getId();
            int count = cartService.getCartItemCount(memberId);
            cartNavButton.setText("My Cart" + (count > 0 ? "  (" + count + ")" : ""));
        }

        // Load campaigns into combo box
        loadedCampaigns = campaignRepository.findAll();
        campaignCombo.getItems().clear();
        for (Campaign c : loadedCampaigns) {
            campaignCombo.getItems().add(c.getName() + " (ID: " + c.getId() + ")");
        }
        if (!loadedCampaigns.isEmpty()) {
            campaignCombo.getSelectionModel().selectFirst();
        }
    }

    @FXML
    private void onSalesReportClicked() {
        LocalDate start = startDatePicker.getValue();
        LocalDate end = endDatePicker.getValue();
        if (start == null || end == null) {
            reportOutput.setText("Please select both start and end dates.");
            return;
        }
        if (start.isAfter(end)) {
            reportOutput.setText("Start date must be before end date.");
            return;
        }

        Map<String, Object> report = reportService.generateSalesReport(start, end);
        StringBuilder sb = new StringBuilder();
        sb.append("                         IPOS-PU Sales Report\n\n");
        sb.append(String.format("Start Period: %s\n", report.get("startDate")));
        sb.append(String.format("End Period:   %s\n\n", report.get("endDate")));

        // Table header matching Appendix 8
        sb.append(String.format(" %-14s| %-18s| %-14s| %-14s| %-10s\n",
                "Item ID", "Description", "Sold, packs", "Unit price, \u00a3", "Total, \u00a3"));
        sb.append("-".repeat(78)).append("\n");

        @SuppressWarnings("unchecked")
        List<Map<String, Object>> items = (List<Map<String, Object>>) report.get("items");
        for (Map<String, Object> item : items) {
            sb.append(String.format(" %-14s| %-18s| %-14d| %-14.2f| %-10.2f\n",
                    item.get("productId"),
                    item.get("productName"),
                    item.get("quantitySold"),
                    item.get("unitPrice"),
                    item.get("totalSales")));
        }

        // Total row matching Appendix 8: "Total online sales for period"
        sb.append("-".repeat(78)).append("\n");
        sb.append(String.format(" %-33s| %-14d| %-14s| %-10.2f\n",
                "Total online sales for period", report.get("totalQuantity"), "N/A", report.get("grandTotal")));

        sb.append(String.format("\nGenerated: %s\n", LocalDate.now()));
        sb.append("Generated by IPOS-PU Operations\n");

        reportOutput.setText(sb.toString());
    }

    @SuppressWarnings("unchecked")
    @FXML
    private void onCampaignReportClicked() {
        LocalDate start = startDatePicker.getValue();
        LocalDate end = endDatePicker.getValue();
        if (start == null || end == null) {
            reportOutput.setText("Please select both start and end dates.");
            return;
        }
        if (start.isAfter(end)) {
            reportOutput.setText("Start date must be before end date.");
            return;
        }

        Map<String, Object> report = reportService.generateCampaignReport(start, end);
        StringBuilder sb = new StringBuilder();
        sb.append("                    IPOS-PU Advert Campaigns Report\n\n");
        sb.append(String.format("Start Period: %s\n", report.get("startDate")));
        sb.append(String.format("End Period:   %s\n", report.get("endDate")));

        List<Map<String, Object>> campaigns = (List<Map<String, Object>>) report.get("campaigns");
        sb.append(String.format("Active campaigns: %d\n\n", report.get("activeCampaigns")));

        if (campaigns.isEmpty()) {
            sb.append("No campaigns found for the selected period.\n");
        } else {
            // Campaign header table matching Appendix 9
            sb.append(String.format(" %-14s| %-16s| %-16s| %-16s| %-14s\n",
                    "Campaign ID", "Start Date/Time", "End Date/Time", "Items included", "Discount, %"));
            sb.append("-".repeat(80)).append("\n");

            for (Map<String, Object> campaign : campaigns) {
                String discountStr = String.format("%.0f%%", campaign.get("discountPercentage"));
                sb.append(String.format(" %-14s| %-16s| %-16s| %-16s| %-14s\n",
                        campaign.get("campaignId"),
                        campaign.get("startDate"),
                        campaign.get("endDate"),
                        campaign.get("itemsIncluded"),
                        discountStr));
            }

            // Per-campaign sold items tables
            for (Map<String, Object> campaign : campaigns) {
                sb.append(String.format("\n  %s\n", campaign.get("campaignId")));
                sb.append(String.format("  %-35s\n", "Sold"));
                sb.append(String.format("  %-10s| %-18s| %-12s| %-14s| %-14s\n",
                        "ID", "Description", "Discount", "Items sold", "Total Sales, \u00a3"));
                sb.append("  " + "-".repeat(72)).append("\n");

                List<Map<String, Object>> soldItems = (List<Map<String, Object>>) campaign.get("soldItems");
                for (Map<String, Object> item : soldItems) {
                    sb.append(String.format("  %-10s| %-18s| %-12s| %-14d| %-14.2f\n",
                            item.get("productId"),
                            item.get("productName"),
                            item.get("discount") + "%",
                            item.get("itemsSold"),
                            item.get("totalSales")));
                }
                sb.append(String.format("  %-43s| %-14s| %-14.2f\n",
                        "Total Sales in campaign:", "", campaign.get("totalSalesInCampaign")));
            }
        }

        sb.append(String.format("\nGenerated: %s\n", LocalDate.now()));
        sb.append("Generated by IPOS-PU Operations\n");
        reportOutput.setText(sb.toString());
    }

    @SuppressWarnings("unchecked")
    @FXML
    private void onEngagementReportClicked() {
        int selectedIdx = campaignCombo.getSelectionModel().getSelectedIndex();
        if (selectedIdx < 0 || loadedCampaigns.isEmpty()) {
            reportOutput.setText("Please select a campaign from the dropdown.");
            return;
        }

        Long campaignDbId = loadedCampaigns.get(selectedIdx).getId();
        Map<String, Object> report = reportService.generateCampaignEngagementReport(campaignDbId);

        StringBuilder sb = new StringBuilder();
        sb.append("                Customer Campaign Engagement Report\n\n");
        sb.append(String.format("Campaign ID: %s\n", report.get("campaignId")));
        sb.append(String.format("Campaign Description: %s\n", report.get("description")));
        sb.append(String.format("Start Period:  %s\n", report.get("startDate")));
        sb.append(String.format("End Period:    %s\n\n", report.get("endDate")));

        // Table header matching Appendix 10
        sb.append(String.format(" %-16s| %-24s| %-14s| %-12s| %-24s\n",
                "Counter ID", "Counter description", "Hits count", "Purchases", "Conversion Rate"));
        sb.append("-".repeat(96)).append("\n");

        List<Map<String, Object>> counters = (List<Map<String, Object>>) report.get("counters");
        for (Map<String, Object> counter : counters) {
            sb.append(String.format(" %-16s| %-24s| %-14s| %-12s| %-24s\n",
                    counter.get("counterId"),
                    counter.get("counterDescription"),
                    counter.get("hitsCount"),
                    counter.get("purchases"),
                    counter.get("conversionRate")));
        }

        sb.append(String.format("\nGenerated: %s\n", LocalDate.now()));
        sb.append("Generated by IPOS-PU Operations\n");
        reportOutput.setText(sb.toString());
    }

    @FXML
    private void onPrintReportClicked() {
        String content = reportOutput.getText();
        if (content == null || content.isEmpty()) {
            reportOutput.setText("No report to print. Generate a report first.");
            return;
        }

        PrinterJob printerJob = PrinterJob.createPrinterJob();
        if (printerJob != null && printerJob.showPrintDialog(reportOutput.getScene().getWindow())) {
            Text printNode = new Text(content);
            printNode.setFont(Font.font("Consolas", 10));
            boolean success = printerJob.printPage(printNode);
            if (success) {
                printerJob.endJob();
            }
        }
    }

    @FXML
    private void onCatalogueClicked() {
        SceneManager.switchTo("/com/ipos/pu/ui/catalogue.fxml");
    }

    @FXML
    private void onCartClicked() {
        SceneManager.switchTo("/com/ipos/pu/ui/cart.fxml");
    }

    @FXML
    private void onOrdersClicked() {
        SceneManager.switchTo("/com/ipos/pu/ui/track-orders.fxml");
    }

    @FXML
    private void onLogoutClicked() {
        SessionManager.clearSession();
        SceneManager.switchTo("/com/ipos/pu/ui/login.fxml");
    }
}
